import { Window } from "@/components/Window";
import { Table } from "@/components/Table";

function Home() {
  const headers = [
    { key: "name", title: "Nome" },
    { key: "age", title: "Idade" },
    { key: "city", title: "Cidade" },
  ];

  const rows = [
    { name: "João", age: "40", city: "Brasília" },
    { name: "Ana", age: "25", city: "Recife" },
    { name: "Ana", age: "23", city: "Porto Alegre" },
    { name: "Fernanda", age: "49", city: "São Paulo" },
    { name: "Ana", age: "24", city: "Curitiba" },
    { name: "Élcio", age: "46", city: "Rio de Janeiro" },
    { name: "João", age: "27", city: "São Paulo" },
    { name: "Rafael", age: "27", city: "Recife" },
    { name: "Rafael", age: "29", city: "São Paulo" },
    { name: "Matheus", age: "57", city: "Fortaleza" },
    { name: "Mariana", age: "43", city: "São Paulo" },
    { name: "Rafael", age: "55", city: "Belo Horizonte" },
    { name: "Fernanda", age: "43", city: "Fortaleza" },
    { name: "Beatriz", age: "54", city: "Manaus" },
    { name: "Carlos", age: "39", city: "Recife" },
    { name: "Beatriz", age: "46", city: "Salvador" },
    { name: "Matheus", age: "33", city: "Porto Alegre" },
    { name: "Mariana", age: "29", city: "Rio de Janeiro" },
    { name: "Mariana", age: "44", city: "São Paulo" },
    { name: "Carlos", age: "33", city: "Salvador" },
    { name: "João", age: "50", city: "Belo Horizonte" },
    { name: "Ana", age: "46", city: "São Paulo" },
    { name: "Matheus", age: "56", city: "Recife" },
    { name: "João", age: "25", city: "Recife" },
    { name: "Ana", age: "48", city: "Recife" },
    { name: "Carlos", age: "46", city: "Recife" },
    { name: "Matheus", age: "57", city: "Manaus" },
    { name: "Fernanda", age: "18", city: "Brasília" },
    { name: "Beatriz", age: "28", city: "Curitiba" },
    { name: "Carlos", age: "28", city: "Fortaleza" },
    { name: "Matheus", age: "32", city: "Porto Alegre" },
    { name: "Matheus", age: "23", city: "São Paulo" },
    { name: "Mariana", age: "28", city: "Fortaleza" },
    { name: "Ana", age: "18", city: "Fortaleza" },
    { name: "Beatriz", age: "54", city: "Fortaleza" },
    { name: "Élcio", age: "21", city: "Manaus" },
    { name: "Beatriz", age: "29", city: "Belo Horizonte" },
    { name: "Carlos", age: "58", city: "Fortaleza" },
    { name: "Beatriz", age: "24", city: "Porto Alegre" },
    { name: "João", age: "26", city: "Belo Horizonte" },
    { name: "João", age: "49", city: "Manaus" },
    { name: "Fernanda", age: "31", city: "São Paulo" },
    { name: "João", age: "23", city: "Brasília" },
    { name: "Beatriz", age: "39", city: "Rio de Janeiro" },
    { name: "Matheus", age: "34", city: "Salvador" },
    { name: "Rafael", age: "45", city: "Salvador" },
    { name: "Rafael", age: "53", city: "Manaus" },
    { name: "Ana", age: "25", city: "São Paulo" },
    { name: "Fernanda", age: "23", city: "Recife" },
    { name: "Lucas", age: "29", city: "Salvador" },
    { name: "Fernanda", age: "28", city: "Fortaleza" },
    { name: "Rafael", age: "38", city: "Recife" },
    { name: "Beatriz", age: "26", city: "Rio de Janeiro" },
    { name: "Beatriz", age: "19", city: "Belo Horizonte" },
    { name: "Lucas", age: "39", city: "Curitiba" },
    { name: "João", age: "28", city: "Fortaleza" },
    { name: "Rafael", age: "50", city: "Belo Horizonte" },
    { name: "Élcio", age: "45", city: "Fortaleza" },
    { name: "Fernanda", age: "40", city: "Brasília" },
    { name: "Ana", age: "28", city: "Curitiba" },
    { name: "Beatriz", age: "50", city: "São Paulo" },
    { name: "Rafael", age: "50", city: "Recife" },
    { name: "Élcio", age: "24", city: "Curitiba" },
    { name: "Carlos", age: "26", city: "Manaus" },
    { name: "Mariana", age: "26", city: "São Paulo" },
    { name: "Rafael", age: "56", city: "São Paulo" },
    { name: "Carlos", age: "57", city: "Curitiba" },
    { name: "Carlos", age: "48", city: "Recife" },
    { name: "João", age: "55", city: "São Paulo" },
    { name: "Fernanda", age: "33", city: "Rio de Janeiro" },
    { name: "Lucas", age: "38", city: "Rio de Janeiro" },
    { name: "Carlos", age: "56", city: "Porto Alegre" },
    { name: "Beatriz", age: "30", city: "Curitiba" },
    { name: "Carlos", age: "38", city: "Brasília" },
    { name: "Mariana", age: "41", city: "Brasília" },
    { name: "Lucas", age: "35", city: "Rio de Janeiro" },
    { name: "Ana", age: "39", city: "Rio de Janeiro" },
    { name: "Rafael", age: "38", city: "Rio de Janeiro" },
    { name: "Ana", age: "47", city: "Salvador" },
    { name: "Matheus", age: "27", city: "Fortaleza" },
    { name: "Lucas", age: "40", city: "Curitiba" },
    { name: "Fernanda", age: "56", city: "Rio de Janeiro" },
    { name: "Mariana", age: "52", city: "Salvador" },
    { name: "Lucas", age: "41", city: "Salvador" },
    { name: "Élcio", age: "19", city: "Manaus" },
    { name: "Lucas", age: "50", city: "Belo Horizonte" },
    { name: "Beatriz", age: "51", city: "Rio de Janeiro" },
    { name: "João", age: "19", city: "Curitiba" },
    { name: "Élcio", age: "18", city: "Recife" },
    { name: "Rafael", age: "35", city: "Manaus" },
    { name: "Matheus", age: "33", city: "Curitiba" },
    { name: "Rafael", age: "36", city: "Recife" },
    { name: "Beatriz", age: "26", city: "Manaus" },
    { name: "Ana", age: "19", city: "Recife" },
    { name: "Matheus", age: "56", city: "Salvador" },
    { name: "Rafael", age: "40", city: "Recife" },
    { name: "João", age: "39", city: "Manaus" },
    { name: "Élcio", age: "55", city: "Curitiba" },
    { name: "Ana", age: "38", city: "Rio de Janeiro" },
    { name: "Élcio", age: "34", city: "Recife" },
  ];

  return (
    <Window>
      <Table headers={headers} rows={rows}></Table>
    </Window>
  );
}

export default Home;
